apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-cli
  namespace: demos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: az-cli
  template:
    metadata:
      labels:
        app: az-cli
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - image: mcr.microsoft.com/azure-cli
        name: az-cli
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
