apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secretprovider-volume-webapp-secrets-demo
  namespace: secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Set to true for using managed identity
    userAssignedIdentityID: $kubeletIdentityclientid # Set the clientID of the user-assigned managed identity to use
    keyvaultName: $keyvaultName # Set to the name of your key vault
    tenantId: $tenantID # The tenant ID of the key vault
    objects: |
      array:
        - |
          objectName: secretvar1
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: secretvar3
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
