apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-secrets-demo
  namespace: secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-secrets-demo
  template:
    metadata:
      labels:
        app: webapp-secrets-demo
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: jannemattila/webapp-update:1.0.9
          name: webapp-secrets-demo
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 150Mi
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: SECRET_VAR2
              valueFrom:
                secretKeyRef:
                  key: secretvar2
                  name: keyvault
          volumeMounts:
            - name: secretsvolume
              mountPath: /mnt/secretsvolume
              readOnly: true
            - name: secretsenv
              mountPath: /mnt/secretsenv
              readOnly: true
      volumes:
        - name: secretsvolume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secretprovider-volume-webapp-secrets-demo
        # https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/298
        - name: secretsenv
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secretprovider-keyvault-webapp-secrets-demo
